/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Asignacion_modificar.java
 *
 * Created on 29-jul-2012, 18:27:54
 */
package iu;

import dominio.Asignacion;
import dominio.Muelle;
import dominio.Vehiculo;
import java.util.ArrayList;
import logicaDeNegocio.Fachada;
import sun.applet.resources.MsgAppletViewer;

/**
 *
 * @author German
 */
public class Asignacion_modificar extends JInternalBaseClass {

    ArrayList todosLosMuelles = null;

    /** Creates new form Asignacion_modificar */
    public Asignacion_modificar() {
        initComponents();
        try {
            todosLosMuelles = Fachada.getInstance().listarMuelles();
            ddlMuelles2.removeAllItems();
            ddlMuelles2.addItem("Seleccionar...");
            for (int i = 0; i < todosLosMuelles.size(); i++) {
                ddlMuelles2.addItem(todosLosMuelles.get(i).toString());
            }
            ddlVehiculo.removeAllItems();
        } catch (Exception e) {
            msgBoxError(e.getMessage());
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ddlVehiculo = new javax.swing.JComboBox();
        btnCancelar = new javax.swing.JButton();
        btnAceptar = new javax.swing.JButton();
        ddlMuelles2 = new javax.swing.JComboBox();

        jLabel1.setText("Muelle");

        jLabel2.setText("Vehículo");

        ddlVehiculo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnAceptar.setText("Confrimar finalización de descarga");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        ddlMuelles2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ddlMuelles2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ddlMuelles2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAceptar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelar))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ddlMuelles2, 0, 238, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ddlVehiculo, 0, 235, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(ddlMuelles2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(ddlVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnAceptar))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
    try {
        int selected = ddlVehiculo.getSelectedIndex();
        if (ddlMuelles2.getSelectedIndex() != 0) {
            Muelle m = (Muelle) todosLosMuelles.get(ddlMuelles2.getSelectedIndex() - 1);
            Asignacion a = (Asignacion) m.getAsignaciones().get(selected);
            Fachada.getInstance().modificarAsignacion(m, a);
            this.closeWindow();
        }

    } catch (Exception ex) {
        msgBoxError(ex.getMessage());
    }
}//GEN-LAST:event_btnAceptarActionPerformed

private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
    this.closeWindow();
}//GEN-LAST:event_btnCancelarActionPerformed

private void ddlMuelles2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ddlMuelles2ActionPerformed
    try {
        ddlVehiculo.removeAllItems();
        if (ddlMuelles2.getItemCount() > 0 && ddlMuelles2.getSelectedIndex() != 0) {
            Muelle m = (Muelle) todosLosMuelles.get(ddlMuelles2.getSelectedIndex() - 1);
            for (int i = 0; i < m.getAsignaciones().size(); i++) {
                Asignacion v = (Asignacion) m.getAsignaciones().get(i);
                ddlVehiculo.addItem(v.getVehiculo().toString());
            }
        }
    } catch (Exception ex) {
        msgBoxError(ex.getMessage());
    }
}//GEN-LAST:event_ddlMuelles2ActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JComboBox ddlMuelles2;
    private javax.swing.JComboBox ddlVehiculo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
