/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Asignacion_modificar.java
 *
 * Created on 29-jul-2012, 18:27:54
 */
package iu;

import dominio.Muelle;
import dominio.Vehiculo;
import java.util.ArrayList;
import logicaDeNegocio.Fachada;
import sun.applet.resources.MsgAppletViewer;

/**
 *
 * @author German
 */
public class Asignacion_modificar extends JInternalBaseClass {
    
    ArrayList todosLosMuelles = null;

    /** Creates new form Asignacion_modificar */
    public Asignacion_modificar() {
        initComponents();
        try {
            todosLosMuelles = Fachada.getInstance().listarMuelles();
            ddlMuelles.removeAllItems();
            ddlMuelles.addItem("Seleccionar...");
            ddlVehiculo.removeAllItems();
        } catch (Exception e) {
            msgBoxError(e.getMessage());
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ddlMuelles = new javax.swing.JComboBox();
        ddlVehiculo = new javax.swing.JComboBox();
        btnCancelar = new javax.swing.JButton();
        btnAceptar = new javax.swing.JButton();

        jLabel1.setText("Muelle");

        jLabel2.setText("Vehículo");

        ddlMuelles.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ddlMuelles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ddlMuellesActionPerformed(evt);
            }
        });

        ddlVehiculo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnAceptar.setText("Confrimar finalización de descarga");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAceptar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ddlVehiculo, 0, 233, Short.MAX_VALUE)
                            .addComponent(ddlMuelles, javax.swing.GroupLayout.Alignment.LEADING, 0, 233, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ddlMuelles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ddlVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnAceptar))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
    
}//GEN-LAST:event_btnAceptarActionPerformed
    
private void ddlMuellesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ddlMuellesActionPerformed
    try {
        ddlVehiculo.removeAllItems();
        if (ddlMuelles.getSelectedIndex() != 0) {
            Muelle m = (Muelle) todosLosMuelles.get(ddlMuelles.getSelectedIndex() - 1);
            for (int i = 0; i < m.getAsignaciones().size(); i++) {
                Vehiculo v = (Vehiculo) m.getAsignaciones().get(i);
                ddlVehiculo.addItem(v.toString());
            }
        }
    } catch (Exception ex) {
        msgBoxError(ex.getMessage());
    }
}//GEN-LAST:event_ddlMuellesActionPerformed

private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
this.closeWindow();
}//GEN-LAST:event_btnCancelarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JComboBox ddlMuelles;
    private javax.swing.JComboBox ddlVehiculo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
