/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ListaSiempreVisible.java
 *
 * Created on 30-jul-2012, 18:53:32
 */
package iu;

import logicaDeNegocio.Fachada;

/**
 *
 * @author German
 */
public class ListaSiempreVisible extends JInternalBaseClass implements utilidades.IObservador {

    /** Creates new form ListaSiempreVisible */
    public ListaSiempreVisible() {
        initComponents();
        try {
            Fachada.getInstance().agregarObservadorDeMuelles(this);
        } catch (Exception ex) {
            msgBoxError(ex.getMessage());
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 394, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 274, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    @Override
    public void actualizar() {
        msgBoxError("se actualizo");
    }
}
