/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Muelle_modificar.java
 *
 * Created on 29-jul-2012, 11:06:49
 */
package iu;


import dominio.Muelle;
import java.util.ArrayList;
import logicaDeNegocio.Fachada;
import utilidades.IObservador;

/**
 *
 * @author German
 */
public class Muelle_modificar extends JInternalBaseClass {

    private ArrayList muelles = null;

    /** Creates new form Muelle_modificar */
    public Muelle_modificar() {
        initComponents();
        actualizar();
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        ddlMuelles = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtDescripcion = new javax.swing.JTextField();
        ddlCriterios = new javax.swing.JComboBox();
        btnCancelar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        jLabel1.setText("Nombre");

        ddlMuelles.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ddlMuelles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ddlMuellesActionPerformed(evt);
            }
        });

        jLabel2.setText("Descripcion");

        jLabel3.setText("Criterio");

        ddlCriterios.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelar))
                    .addComponent(ddlMuelles, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                            .addComponent(txtDescripcion, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                            .addComponent(ddlCriterios, javax.swing.GroupLayout.Alignment.TRAILING, 0, 115, Short.MAX_VALUE))))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ddlMuelles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(ddlCriterios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(jButton1))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
    this.closeWindow();
}//GEN-LAST:event_btnCancelarActionPerformed

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    try {
        Muelle m = (Muelle) muelles.get(ddlMuelles.getSelectedIndex() - 1);        
        //m.setCriterio(ddlCriterios.getSelectedIndex() + 1);
        //m.setDescripcion(txtDescripcion.getText());
        //m.setNombre(txtNombre.getText());
        Fachada.getInstance().modificarMuelle(m, ddlCriterios.getSelectedIndex() + 1, txtDescripcion.getText(), txtNombre.getText());
        this.closeWindow();
    } catch (Exception ex) {
        msgBoxError(ex.getMessage());
    }
}//GEN-LAST:event_jButton1ActionPerformed

private void ddlMuellesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ddlMuellesActionPerformed
    try {
        ddlCriterios.removeAllItems();
        if (ddlMuelles.getSelectedIndex() > 0) {

            Muelle m = (Muelle) muelles.get(ddlMuelles.getSelectedIndex() - 1);

            for (int i = 0; i < utilidades.enums.Criterio.values().length; i++) {
                ddlCriterios.addItem(utilidades.enums.Criterio.values()[i].toString());                
            }
            ddlCriterios.setSelectedIndex(m.getCriterio() - 1);
            this.txtDescripcion.setText(m.getDescripcion());
            this.txtNombre.setText(m.getNombre());
        }
    } catch (Exception ex) {
        msgBoxError(ex.getMessage());
    }
}//GEN-LAST:event_ddlMuellesActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JComboBox ddlCriterios;
    private javax.swing.JComboBox ddlMuelles;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables

    
    public void actualizar() {
        try {
            ddlCriterios.removeAllItems();
            ddlMuelles.removeAllItems();
            ddlMuelles.addItem("Seleccione un muelle");
            muelles = Fachada.getInstance().listarMuelles();
            for (int i = 0; i < muelles.size(); i++) {
                Muelle m = (Muelle) muelles.get(i);
                ddlMuelles.addItem(m.toString());
            }

        } catch (Exception ex) {
            msgBoxError(ex.getMessage());
            this.closeWindow();
        }
    }
}
